#!/bin/bash

pip install --upgrade youtube-dl
echo -ne "3333333333333333\r"
sleep 1
echo -ne "2222222222222222\r"
sleep 1
echo -ne "1111111111111111\r"
sleep 1
clear
pip install --upgrade beets
echo -ne "3333333333333333\r"
sleep 1
echo -ne "2222222222222222\r"
sleep 1
echo -ne "1111111111111111\r"
sleep 1
clear

#set -eu
#--download-archive ${CONFIG}.desc \
#
if [[ $1 =~ ^.*youtu.*$ ]]; then

    echo "${bold}Youtube-dl${normal}"
    TMP_DIR="$(mktemp -dt musica-dl.XXXXXX)"
    OUT_DIR="/storage/emulated/0/Music/musica-dl"
    CONFIG="${HOME}/.config/musica-dl"

    mkdir "${TMP_DIR}"/raw "${TMP_DIR}"/cooked

     #  youtube-dl \
     #          --ignore-errors \
     #          --write-thumbnail \
     #          --skip-download \
     #          --output "${TMP_DIR}/cooked/%(title)s" \
     #          -- "$@"

     youtube-dl \
         --ignore-errors \
         --download-archive descargados.txt \
         --format 'bestaudio' \
         --output "${TMP_DIR}/raw/%(title)s" \
         -- "$@"

     for file in "${TMP_DIR}/raw/"*; do
         ffmpeg \
             -hide_banner \
             -i "$file" \
             -codec:a libmp3lame \
             -qscale:a 2 \
             -vn \
             -map_metadata -1 \
             "${TMP_DIR}/cooked/${file##*/}.mp3"
         done

#       if command -v eyeD3 >/dev/null; then
#               eyeD3 --remove-all "${TMP_DIR}"/cooked/*.mp3
#       fi

mkdir -p "${OUT_DIR}"
mv -f "${TMP_DIR}"/cooked/* "${OUT_DIR}"
rm -rf "${TMP_DIR}"

elif [[ $1 =~ ^.*nourlselected.*$ ]]; then
    echo "ERROR1"
else
    echo Unhandled URL type: $1
fi
